config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users
  resources :users, except: [:new, :create]

  scope module: 'mailbox' do
    get 'inbox', to: 'mailbox#inbox'

    resources :mailboxer_conversations, path: 'conversations', except: [:index], controller: 'conversations'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable
  acts_as_messageable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :password])
  end

  def authorization_error
    redirect_to root_path, flash: { error: 'Unauthorized action' }
  end

  def mailbox
    @mailbox ||= current_user.mailbox
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    if user_signed_in?
      @users = User.all
      render 'users/index'
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/mailbox/conversations_controller.rb
module Mailbox
  class ConversationsController < ApplicationController
    def show

    end
  end
end

app/controllers/mailbox/mailbox_controller.rb
module Mailbox
  class MailboxController < ApplicationController
    before_action :mailbox

    def inbox

    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if @user.id != current_user.id
      authorization_error
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.id != current_user.id
      authorization_error
    else
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.id == current_user.id
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      authorization_error
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
%ul.nav.nav-pills
  - if user_signed_in?
    %li
      %a{href: root_path} Home
    %li
      %a{href: inbox_path} Mailbox
    %li
      %a{href: "#"}
        = "You are currently signed in as: #{current_user.name}"
    %li
      %a{href: destroy_user_session_path, "data-method": :delete} Sign out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title Mailbox
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    .container
      = render partial: 'layouts/header'

      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} container"}
            %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
            = content_tag :div, msg, :id => "flash_#{name}"

      = yield

app/views/mailbox/conversations/_actions.html.haml
.well.well-sm
  = link_to 'Reply', '#', class: 'btn btn-secondary'
  = link_to 'Reply All', '#', class: 'btn btn-secondary'

app/views/mailbox/conversations/_message.html.haml
.panel.panel-default
  .panel-heading.date-box{"data-toggle" => "collapse", :href => "#collapse1"}
    %h5 First mail
    From: Bianca
    .message-date
      Date: Jan 19, 12:16
  #collapse1.panel-collapse.collapse
    .panel-body
      Hello

.panel.panel-default
  .panel-heading.date-box{"data-toggle" => "collapse", :href => "#collapse2"}
    %h5 Thread - new policy
    From: Bianca, User
    .message-date
      Date: Jan 17, 12:00
  #collapse2.panel-collapse.collapse
    .panel-body
      Hello all, this is ...

app/views/mailbox/conversations/show.html.haml
.page-header
  %h1 Inbox

.row
  = render partial: 'mailbox/shared/folders'

  .container-three.col-lg-10.col-md-10.col-sm-11.col-xs-12.email.no-lr-padding
    .conversation-content
      .options-bar
        = render partial: 'mailbox/mailbox/options'

      .jumbotron
        .mailbox-conversations
          = render partial: 'mailbox/conversations/message'

    .conversation-actions
      = render partial: 'mailbox/conversations/actions'

app/views/mailbox/mailbox/_conversations.html.haml
%table.table.table-hover.table-condensed
  %tbody
    %tr.cursor-hand{"data-href": "/conversations/1"}
      %td 1
      %td From: Bianca
      %td
        %b First mail
        Hello
      %td Jan 19, 12:16
    %tr
      %td 2
      %td Bianca, User
      %td
        %b Thread - new policy
        Hello all, this is ...
      %td Jan 17, 12:00


%ul.pagination.pagination-sm
  %li.disabled
    %a{:href => "#"} «
  %li.active
    %a{:href => "#"} 1
  %li
    %a{:href => "#"} 2
  %li
    %a{:href => "#"} 3
  %li
    %a{:href => "#"} 4
  %li
    %a{:href => "#"} 5
  %li
    %a{:href => "#"} »

app/views/mailbox/mailbox/_options.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %a.navbar-brand{:href => "#"} New

    #bs-example-navbar-collapse-2.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "#"} Link

        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Actions
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Delete
            %li
              %a{:href => "#"} Spam

      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#"} Other Action

app/views/mailbox/mailbox/inbox.html.haml
.page-header
  %h1 Inbox

.row
  = render partial: 'mailbox/shared/folders'

  .container-three.col-lg-10.col-md-10.col-sm-11.col-xs-12.email.no-lr-padding
    .conversation-content
      .options-bar
        = render partial: 'mailbox/mailbox/options'

      .jumbotron
        .mailbox-conversations
          = render partial: 'mailbox/mailbox/conversations'

app/views/mailbox/shared/_folders.html.haml
.container-three.col-lg-2.col-md-2.col-sm-3.col-xs-12.email.no-lr-padding
  %ul.list-group
    %li.list-group-item{role: "presentation"}
      %span.badge 1
      %a{href: inbox_path}
        .atom
          %span.icon
            %i.fa.fa-envelope-o
          %h6
            Inbox
    %li.list-group-item{role: "presentation"}
      %a{href: '#'}
        .atom
          %span.icon
            %i.fa.fa-sign-out
          %h6 Sent
    %li.list-group-item{role: "presentation"}
      %a{href: '#'}
        .atom
          %span.icon
            %i.fa.fa-trash-o
          %h6 Trash

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field.form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'

  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/users/edit.html.haml
.page-header
  %h1 Editing user
%br

= render 'form'

= link_to 'Show', @user, class: 'btn btn-secondary'
= link_to 'Back', users_path, class: 'btn btn-secondary'

app/views/users/index.html.haml
.page-header
  %h1 Listing users

%br
%br

.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Email
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= link_to 'Show', user
          - if user.id == current_user.id
            %td= link_to 'Edit', edit_user_path(user)
            %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }
          - else
            %td
            %td

app/views/users/new.html.haml
.page-header
  %h1 New user
%br

= render 'form'

= link_to 'Back', users_path, class: 'btn btn-secondary'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary'
= link_to 'Back', users_path, class: 'btn btn-secondary'